-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgigGosAYqAD5TPTnu
0v3w3sgss8C4vbQB/eTMyN7cD2SgCgYIKoZIzj0DAQehRANCAASSgknOkMWehLNe
VK/Px44qru1A62vp3LNWwzgswjDiHGujQnFfR9l4R/izEq/Ael4CgAOlcFP4aR6i
SWRcydy8
-----END PRIVATE KEY-----